### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by Unknown78** [Devyatyi9/usm_sbt_patcher#1]
What is this? What does it do? How to use it? How do you extract/convert the usm format in the first place?

I'd like to have it back as .mp4 and .srt file, is that possible?

**Comment by Devyatyi9** [comment]
@Unknown78 this code is used to read subtitles from usm files and export it. I tried changing the subtitle text inside these files, but it didn't work for all files.
There is also [a raw program](https://mega.nz/folder/fJdg2TgD#GPGWFhRMtm-VeN3YTspudg) for converting mp4 to usm along with subtitles, it was written by art-serious, I don’t know if it is registered on github. I added a little to his code, it's a pity that while the usm format cannot be converted to usm.

at least it works exactly for files from honkai impact

**Comment by Unknown78** [comment]
@Devyatyi9  If I want to convert any .usm file into .mp4 video and .srt subtitle, just like the old version of honkai impact around some months ago, what should I do?

**Comment by Devyatyi9** [comment]
@Unknown78 use VGMToolbox
.adx is sound and .m2v is video
![2022-12-13_18-51-42](https://user-images.githubusercontent.com/5161472/207366207-493c8640-ae62-4f15-ae53-c33ffefbd379.png)
![2022-12-13_18-55-13](https://user-images.githubusercontent.com/5161472/207366951-4dc9e9d2-5f28-4f94-9afe-7cd2b7472811.png)

And to extract subtitles use [this tool](https://mega.nz/file/XFNGWQ7I#4yUnzUVljtLFvPkjoBi569vtPKzqMDkEU7WHp7d0qjE) from cmd.
Example:
hi3_usm_srt_tool.exe -extractSbt "usm_videos/Story_06.usm"
hi3_usm_srt_tool.exe -extractSbt "usm_videos/Story_06.usm" "srt/Story_06.srt"

although I am not sure that the subtitle timings will be converted correctly for some files

Also, there are mp4 videos before 5.8
https://drive.google.com/file/d/1ij3SBAaGuzoAFYiownkUMXoL8ogYUcKq/

**Comment by Unknown78** [comment]
@Devyatyi9 

When I'm extracting the .usm file, I got .m2v as video but .hca as sound instead of .adx.
Is that okay?

I could run ffmpeg with this command to combine it just fine though
`ffmpeg -i 6.2PV_d8052964b502223025b122ef40c2ca5d_40534656.m2v -i 6.2PV_d8052964b502223025b122ef40c2ca5d_40534641.hca 6.2PV_d8052964b502223025b122ef40c2ca5d_40534656.mp4`

<hr>

And now I have a different problem,
After successfully combined the .m2v and .hca with the command above and extracting the subtitles into .srt.
The extracted .srt file has multiple lines, but only the first line that appears in the video.
Every other line is just not show up, I run on Media Player Classic and also VLC player, and the result is the same.

This is the ffmpeg log:
[6.2PV_ffmpeg_log.txt](https://github.com/Devyatyi9/HI3rd_usm_sbt_patcher/files/10221168/6.2PV_ffmpeg_log.txt)

This is the extracted .srt file: 
[6.2PV_d8052964b502223025b122ef40c2ca5d_40534656.txt](https://github.com/Devyatyi9/HI3rd_usm_sbt_patcher/files/10221213/6.2PV_d8052964b502223025b122ef40c2ca5d_40534656.txt)
I upload it as .txt because of GitHub limitation.

**Comment by Devyatyi9** [comment]
@Unknown78 .hca is also a CRI audio format, should work.
in the srt file, there is probably an error in some time values. can be edited through the subtitle editor like Aegisub.
it is necessary to compare with the original usm file, although I never wrote the reading template of this format for 010 Editor.
Are there any problems with video and sound?
By the way, I use Daum Potplayer because it supports many formats and codecs.

I had an idea to rewrite this code in another language like C#
although I have already done, together with another person, what it was all done for - to replace English subtitles with Russian ones.
Though only for old cutscenes.

if you want to compare these values manually through a hex editor, then [here is a description](https://github.com/Devyatyi9/HI3rd_usm_sbt_patcher/blob/master/USM%20Video%20format.txt) of @SBT structures in which subtitles are written.
Check start time and end time, it's integer value (uint/sint).
![Dbk5PBB](https://user-images.githubusercontent.com/5161472/207656219-3d85355e-dddd-4868-b9ae-422d2874c367.png)
Ok, I already checked it, and the values are the same, strange, maybe the problem is null characters, then you just need to remove them from the srt file, for example, using Notepad++

**Comment by Unknown78** [comment]
@Devyatyi9 

There are no problem with video or sound at all, just the subtitle that has the problem.

Thanks for recommending me a new player, according to [someone's detailed review](https://berofusion.blogspot.com/p/testarea.html), it seems that PotPlayer is a good player.
But in my case, the first line won't even shown at all, the subtitle couldn't be loaded.

And I think I found that there is a bug in the `hi3_usm_srt_tool.exe` program.

<hr>

Please take a look at this screenshot.
![screenshot 1671114811](https://user-images.githubusercontent.com/25132599/207887908-b1e4c546-0c93-456e-b071-43c305d6de91.png)

In your description at [USM Video format.txt](https://github.com/Devyatyi9/HI3rd_usm_sbt_patcher/blob/master/USM%20Video%20format.txt), it says:

> time end = time begin + time end

I would prefer to call it `time duration` instead of `time end` twice tough.
so `time end` = `time begin` + `time duration`

But the program extract the `time end` as `time duration` only, without adding it up with `time begin`.
Take a look on the screenshot, next right to `--->` is the `time duration` and not the `time end`.
The .srt is in incorrect format. And that's why it failed to be load properly.

The program need to be fixed.

P.S. I'm on SEA server if that matters....

**Comment by Unknown78** [comment]
@Devyatyi9  How do I get the program to be fixed?

**Comment by Devyatyi9** [comment]
> @Devyatyi9 How do I get the program to be fixed?

Sorry for the long answer.
I just forgot that someone still needs me on github.
Yes, I need to correct these descriptions, I made them in a hurry just for myself when I was just dealing with this format.
And I think it doesn't matter which server you're playing on, in my opinion the file is the same.

I can try to explain what is needed in order to run it all and change the code. Although I would prefer to rewrite it all into a more popular language so that there are fewer problems.

**Comment by Devyatyi9** [comment]
1. Install VSCode https://code.visualstudio.com/download
2. Install Haxe https://haxe.org/download/
3. Install C++ library for Haxe https://lib.haxe.org/p/hxcpp/
4. You will also need a Visual Studio C++ compiler, or different C++ compiler like [MinGW](https://www.mingw-w64.org/)
5. Haxe [extensions](https://github.com/vshaxe/vshaxe/wiki/Debugging) for VSCode:
nadako.vshaxe
vshaxe.hxcpp-debugger
